# Generated by Django 4.2.6 on 2023-10-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hateykhori', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(default=1, upload_to='categories/'),
            preserve_default=False,
        ),
    ]
